# Generated by Django 3.0.7 on 2020-07-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.SlugField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
