# Generated by Django 3.0.7 on 2020-07-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20200722_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='votes',
        ),
        migrations.DeleteModel(
            name='UserVotes',
        ),
    ]
