# Generated by Django 3.0.8 on 2020-07-30 17:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20200722_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', multiselectfield.db.fields.MultiSelectField(choices=[('pubg', 'Pubg'), ('basketball', 'Basketball'), ('football', 'Football'), ('cricket', 'Cricket')], max_length=32)),
            ],
        ),
    ]
